language: node_js
node_js:
  - "lts/*"
install:
  - npm install
script:
  #- npm run eslint
  - npm test
  - npm run coveralls
  - npm run generate-docs
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: docs
  on:
    branch: master